name: yy_new
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.0
  event_bus: ^2.0.0
  provider: ^6.0.5
  flutter_easyloading: ^3.0.5
  dio: ^5.1.1
  local_auth: ^2.1.6
  flutter_swiper_null_safety: ^1.0.2
  webview_flutter: ^4.2.0
  pull_to_refresh: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  dotted_border: ^2.0.0+3
  proste_indexed_stack: ^0.2.4
  fluttertoast: ^8.0.7
  package_info_plus: ^3.1.2
  device_info_plus: ^8.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - imgs/logo@2x.png
    - imgs/default_avatar.png
    - imgs/tab_home_unselect.png
    - imgs/tab_game_unselect.png
    - imgs/facebook@2x.png
    - imgs/google@2x.png
    - imgs/instagram@2x.png
    - imgs/checkbox.png
    - imgs/care@2x.png
    - imgs/articles@2x.png
    - imgs/tab-icon-home.png
    - imgs/badge-soon.png
    - imgs/badge-unverified.png
    - imgs/badge-verified.png
    - imgs/icon-hands-helping.png
    - imgs/tab-icon-scan-disabled.png
    - imgs/checkbox-checked.png
    - imgs/onboarding-bg.png
    - imgs/summary-bg.png
    - imgs/onboarding-mascot.png
    - imgs/what-is-resiklos.png
    - imgs/importance-of-resiklos.png
    - imgs/placeholder_avatar.png
    - imgs/verification_bg_image.png
    - imgs/verify_email_image.png
    - imgs/verify_success_image.png
    - imgs/verify_kyc_person.png
    - imgs/verfiy_id.png
    - imgs/verify_person.png
    - imgs/verify_face_id.png
    - imgs/img.png
    - imgs/merchant_top_cover.png
    - imgs/rp_bg.png
    - imgs/camera.png
    - imgs/wallet-header.png
    - imgs/wallet/bnb_logo.svg
    - imgs/wallet/tether_usdt_logo.svg
    - imgs/svg/bnb.svg
    - imgs/svg/usdt.svg
    - imgs/svg/wallet_bg.svg
    - imgs/svg/gem.svg
    - imgs/svg/summary_bg.svg
    - imgs/svg/verify_email.svg
    - imgs/svg/wallet_header.svg
    - imgs/svg/external_link.svg
    - imgs/svg/vouchers_icon.svg
    - imgs/svg/rp_icon.svg
    - imgs/svg/affiliates_icon.svg
    - imgs/svg/scan_icon.svg
    - imgs/svg/transfer_icon.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
